source "https://rubygems.org"

# Put libraries here that you want to spike on
# gem 'celluloid'


# Dev tools
group :development do
  gem 'rspec', "~> 3"

  gem 'pry'
  gem 'pry-doc'
  gem 'guard', "~> 2"
  gem 'guard-rspec'

  # the proper way to include OS fs event hooks
  gem 'rb-fsevent', require: true

  gem 'method_profiler'
end
